apiVersion: v1
kind: Service
metadata:
  name: subgen-redis
  namespace: subgen
spec:
  selector:
    app: subgen-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP