apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: subgen

resources:
  - 00-namespace.yaml
  - 10-configmap.yaml
  - 11-pvc-data.yaml
  - 20-redis-deployment.yaml
  - 21-redis-service.yaml
  - 30-api-deployment.yaml
  - 31-api-service.yaml
  - 40-worker-deployment.yaml